export const APP_ROUTES = {
  dashboard: '/',
  auditLogView: (id: string) => `/audit-logs/${id}/show`,
  auditLogs: '/audit-logs',
  emailCreate: '/emails/create',
  emailView: (id: string) => `/emails/${id}/show`,
  emails: '/emails',
  login: '/login',
  notifications: '/notifications',
  organizationEdit: (id: string) => `/organizations/${id}`,
  organizationProfile: '/organization-profile',
  organizationSettings: '/organization-settings',
  organizationView: (id: string) => `/organizations/${id}/show`,
  organizations: '/organizations',
  parameters: '/parameters',
  parameterEdit: (id: string) => `/parameters/${id}`,
  permissions: '/permissions',
  registerOrganization: '/register-organization',
  roleCreate: '/roles/create',
  roleEdit: (id: string) => `/roles/${id}`,
  roles: '/roles',
  systemLogView: (id: string) => `/system-logs/${id}/show`,
  systemLogs: '/system-logs',
  templateCreate: '/templates/create',
  templateEdit: (id: string) => `/templates/${id}`,
  templates: '/templates',
  userCreate: '/users/create',
  userAccess: '/user-access',
  userEdit: (id: string) => `/users/${id}`,
  userProfile: '/user-profile',
  userSettings: '/user-settings',
  userView: (id: string) => `/users/${id}/show`,
  users: '/users',
} as const
