export const APP_ROUTES = {
  dashboard: '/',
  login: '/login',
  organizationEdit: (id: string) => `/organizations/${id}`,
  organizationProfile: '/organization-profile',
  organizationSettings: '/organization-settings',
  organizationView: (id: string) => `/organizations/${id}/show`,
  organizations: '/organizations',
  parameters: '/parameters',
  parameterEdit: (id: string) => `/parameters/${id}`,
  permissions: '/permissions',
  registerOrganization: '/register-organization',
  roleCreate: '/roles/create',
  roleEdit: (id: string) => `/roles/${id}`,
  roles: '/roles',
  userCreate: '/users/create',
  userAccess: '/user-access',
  userEdit: (id: string) => `/users/${id}`,
  userProfile: '/user-profile',
  userSettings: '/user-settings',
  userView: (id: string) => `/users/${id}/show`,
  users: '/users',
} as const
