export const APP_ROUTES = {
  dashboard: '/',
  login: '/login',
  organizationEdit: (id: string) => `/organizations/${id}`,
  organizationProfile: '/organization-profile',
  organizationShow: (id: string) => `/organizations/${id}/show`,
  organizations: '/organizations',
  parameters: '/parameters',
  permissions: '/permissions',
  registerOrganization: '/register-organization',
  roles: '/roles',
  userCreate: '/users/create',
  userEdit: (id: string) => `/users/${id}`,
  userProfile: '/user-profile',
  userShow: (id: string) => `/users/${id}/show`,
  users: '/users',
} as const
