<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Isopoh.Cryptography.Argon2" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.7" />
    <PackageReference Include="Myce.FluentValidator" Version="1.7.0" />
    <PackageReference Include="Myce.Response" Version="1.3.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\01.Shared\Shared.Application\Shared.Application.csproj" />
    <ProjectReference Include="..\IAM.Domain\IAM.Domain.csproj" />
  </ItemGroup>
</Project>
